# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import base_pb2 as base__pb2

GRPC_GENERATED_VERSION = '1.72.0rc1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in base_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PeerEdgeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AsyncOperations = channel.stream_stream(
                '/giggityflix_grpc_peer.PeerEdgeService/AsyncOperations',
                request_serializer=base__pb2.PeerMessage.SerializeToString,
                response_deserializer=base__pb2.EdgeMessage.FromString,
                _registered_method=True)
        self.WebRTCOperations = channel.unary_unary(
                '/giggityflix_grpc_peer.PeerEdgeService/WebRTCOperations',
                request_serializer=base__pb2.EdgeWebRTCMessage.SerializeToString,
                response_deserializer=base__pb2.PeerWebRTCMessage.FromString,
                _registered_method=True)


class PeerEdgeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AsyncOperations(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WebRTCOperations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeerEdgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AsyncOperations': grpc.stream_stream_rpc_method_handler(
                    servicer.AsyncOperations,
                    request_deserializer=base__pb2.PeerMessage.FromString,
                    response_serializer=base__pb2.EdgeMessage.SerializeToString,
            ),
            'WebRTCOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.WebRTCOperations,
                    request_deserializer=base__pb2.EdgeWebRTCMessage.FromString,
                    response_serializer=base__pb2.PeerWebRTCMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'giggityflix_grpc_peer.PeerEdgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('giggityflix_grpc_peer.PeerEdgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PeerEdgeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AsyncOperations(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/giggityflix_grpc_peer.PeerEdgeService/AsyncOperations',
            base__pb2.PeerMessage.SerializeToString,
            base__pb2.EdgeMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WebRTCOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/giggityflix_grpc_peer.PeerEdgeService/WebRTCOperations',
            base__pb2.EdgeWebRTCMessage.SerializeToString,
            base__pb2.PeerWebRTCMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
