# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\x12\x15giggityflix_grpc_peer\"\x1c\n\x1a\x43\x61talogAnnouncementRequest\"2\n\x1b\x43\x61talogAnnouncementResponse\x12\x13\n\x0b\x63\x61talog_ids\x18\x01 \x03(\t\"B\n\x10\x46ileOfferRequest\x12.\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x1f.giggityflix_grpc_peer.FileInfo\"5\n\x08\x46ileInfo\x12\x15\n\rrelative_path\x18\x01 \x01(\t\x12\x12\n\nsize_bytes\x18\x02 \x01(\x03\"H\n\x11\x46ileOfferResponse\x12\x33\n\x05\x66iles\x18\x01 \x03(\x0b\x32$.giggityflix_grpc_peer.CatalogedInfo\":\n\rCatalogedInfo\x12\x15\n\rrelative_path\x18\x01 \x01(\t\x12\x12\n\ncatalog_id\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CATALOGANNOUNCEMENTREQUEST']._serialized_start=40
  _globals['_CATALOGANNOUNCEMENTREQUEST']._serialized_end=68
  _globals['_CATALOGANNOUNCEMENTRESPONSE']._serialized_start=70
  _globals['_CATALOGANNOUNCEMENTRESPONSE']._serialized_end=120
  _globals['_FILEOFFERREQUEST']._serialized_start=122
  _globals['_FILEOFFERREQUEST']._serialized_end=188
  _globals['_FILEINFO']._serialized_start=190
  _globals['_FILEINFO']._serialized_end=243
  _globals['_FILEOFFERRESPONSE']._serialized_start=245
  _globals['_FILEOFFERRESPONSE']._serialized_end=317
  _globals['_CATALOGEDINFO']._serialized_start=319
  _globals['_CATALOGEDINFO']._serialized_end=377
# @@protoc_insertion_point(module_scope)
